int _putchar(char c);
void _puts_recursion(char *s);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int _sqrt_finder(int k, int i);
int _sqrt_recursion(int n);
int _prime_finder(int k, int i);
int is_prime_number(int n);
char *str_slice(char *src);
int is_palindrome(char *s);
